daemonset:
  enabled: true

filebeatConfig:
  filebeat.yml: |
    filebeat.inputs:
      - type: container
        paths:
          - /var/log/containers/*.log
        processors: []

    output.elasticsearch:
      hosts: ["http://elk-elasticsearch:9200"]
      username: "elastic"
      password: "Btssio75000"

tolerations:
  - operator: "Exists"

nodeSelector:
  kubernetes.io/os: linux
