filebeatConfig:
  filebeat.yml: |
    filebeat.inputs:
      - type: container
        paths:
          - /var/log/containers/containers/*.log
        processors:
          - add_kubernetes_metadata: ~

    output.elasticsearch:
      hosts: ["http://elk-elasticsearch.monitoring.svc.cluster.local:9200"]
      username: "elastic"
      password: "Btssio75000"

extraVolumeMounts:
  - name: varlog
    mountPath: /var/log/containers/
    readOnly: true

daemonset:
  enabled: true

resources:
  limits:
    memory: 256Mi
    cpu: 200m
  requests:
    memory: 128Mi
    cpu: 100m
