
image: "docker.elastic.co/beats/filebeat"
imageTag: "8.5.1"

replicas: 1

daemonset:
  enabled: true
  extraEnvs: {}
  resources:
    requests:
      cpu: "100m"
      memory: "100Mi"
    limits:
      cpu: "1000m"
      memory: "200Mi"
  filebeatConfig:
    filebeat.yml: |
      filebeat.inputs:
      - type: container
        paths:
          - /var/log/containers/*.log
        processors:
        - add_kubernetes_metadata:
            host: ${NODE_NAME}
            matchers:
            - logs_path:
                logs_path: "/var/log/containers/"

      output.elasticsearch:
        host: '${NODE_NAME}'
        hosts: ["http://elasticsearch:9200"]
        protocol: https
  secretMounts: []
