
image:
  registry: docker.io
  repository: bitnami/kibana
  tag: 8.17.2-debian-12-r0

replicaCount: 1

elasticsearch:
  hosts:
    - elasticsearch
  port: 9200

resources:
  requests:
    cpu: 500m
    memory: 1Gi
  limits:
    cpu: 2
    memory: 3Gi

service:
  type: ClusterIP

livenessProbe:
  enabled: true
  initialDelaySeconds: 120
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6
  successThreshold: 1
readinessProbe:
  enabled: true
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6
  successThreshold: 1
persistence:
  enabled: true
  size: 2Gi
  storageClass: "standard"
metrics:
  enabled: false