apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity-deployment
  namespace: ynov
spec:
  replicas: 1
  selector:
    matchLabels:
      app: identity
  template:
    metadata:
      labels:
        app: identity
    spec:
      containers:
        - name: identity
          image: misterleo0/identity.api:latest
          ports:
            - containerPort: 80
          env:
            - name: RedisHost
              value: "redis-service:6379"
            - name: HostRabbitmq
              value: "rabbitmq-service"
          resources:
            requests:
              cpu: "0.5"
              memory: "500Mi"
            limits:
              cpu: "1"
              memory: "1500Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: identity-service
  namespace: ynov
spec:
  selector:
    app: identity
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80