elasticsearch:
  hosts:
    - elk-elasticsearch
  port: 9200

resources:
  limits:
    cpu: 3
    memory: 6Gi
  requests:
    cpu: 1
    memory: 3Gi
livenessProbe:
  enabled: true
  initialDelaySeconds: 120
  periodSeconds: 15
  timeoutSeconds: 20
  failureThreshold: 6
  successThreshold: 1
readinessProbe:
  enabled: true
  initialDelaySeconds: 120
  periodSeconds: 15
  timeoutSeconds: 20
  failureThreshold: 6
  successThreshold: 1


service:
  type: ClusterIP