
web:
  name: web
  namespace: ynov
  replicas: 1
  image:
    repository: misterleo0/web
    tag: latest
  resources:
    requests:
      cpu: "4m"
      memory: "900Mi"
    limits:
      cpu: "1"
      memory: "2000Mi"
  ingressroute:
    name: web-ynov
    namespace: ynov
    dns: webynov.leo.local

sql:
  name: sql
  namespace: ynov
  replicas: 1
  image:
    repository: misterleo0/mssql-linux
    tag: latest
  db:
    password: "Pass@word"

redis:
  name: redis
  namespace: ynov
  replicas: 1
  image:
    repository: misterleo0/redis
    tag: latest
  resources:
    requests:
      cpu: "4m"
      memory: "500Mi"

rabbitmq:
  name: rabbitmq
  namespace: ynov
  replicas: 1
  image:
    repository: misterleo0/rabbitmq
    tag: latest
  ingressroute:
    name: rabbit-ynov
    namespace: ynov
    dns: rabbit.leo.local

jobsApi:
  name: jobs-api
  namespace: ynov
  replicas: 1
  image:
    repository: misterleo0/jobs.api
    tag: latest
  resources:
    requests:
      cpu: "0.5"
      memory: "500Mi"
    limits:
      cpu: "1"
      memory: "1500Mi"

identityApi:
  name: identity-api
  namespace: ynov
  replicas: 1
  image:
    repository: misterleo0/identity.api
    tag: latest
  resources:
    requests:
      cpu: "0.5"
      memory: "500Mi"
    limits:
      cpu: "1"
      memory: "1500Mi"

applicantsApi:
  name: applicants-api
  namespace: ynov
  replicas: 1
  image:
    repository: misterleo0/applicants.api
    tag: latest
  resources:
    requests:
      cpu: "0.5"
      memory: "500Mi"
    limits:
      cpu: "1"
      memory: "1500Mi"