image:
  registry: docker.io
  repository: bitnami/metrics-server
  tag: 0.7.2-debian-12-r16

replicas: 1

resources:
  requests:
    cpu: "200m"
    memory: "250Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

containerPorts:
  https: 8443

livenessProbe:
  enabled: false

readinessProbe:
  enabled: false

service:
  type: ClusterIP
  ports:
    https: 443
apiService:
  create: true
args:
  - --kubelet-insecure-tls
  - --kubelet-preferred-address-types=InternalIP
  - --secure-port=8443
