
prometheus:
  enabled: true
  prometheusSpec:
    replicas: 1
    retention: 1d
    image:
      registry: quay.io
      repository: prometheus/prometheus
      tag: v3.1.0

alertmanager:
  enabled: false
grafana:
  enabled: false