apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-dashboard
  namespace: traefik
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - match: Host(`traefikleo.local`)
      kind: Rule
      services:
        - name: api@internal
          kind: TraefikService
  tls:
    secretName: traefikleo-local-cert
    options:
      name: tls-traefik
      namespace: traefik
---
apiVersion: traefik.io/v1alpha1
kind: TLSOption
metadata:
  name: tls-traefik
  namespace: traefik
spec:
  minVersion: VersionTLS13
  cipherSuites:
    - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
    - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
  sniStrict: true
