apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.rabbitmq.name }}
  namespace: {{ .Values.rabbitmq.namespace }}
spec:
  replicas: {{ .Values.rabbitmq.replicas }}
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: {{ .Values.rabbitmq.image.repository }}:{{ .Values.rabbitmq.image.tag }}
          ports:
            - containerPort: 15672
            - containerPort: 5672
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
  namespace: {{ .Values.rabbitmq.namespace }}
spec:
  selector:
    app: rabbitmq
  ports:
    - name: management
      protocol: TCP
      port: {{ .Values.rabbitmq.service.management.port }}
      targetPort: {{ .Values.rabbitmq.service.management.targetport }}
    - name: messaging
      protocol: TCP
      port: {{ .Values.rabbitmq.service.messaging.port }}
      targetPort: {{ .Values.rabbitmq.service.messaging.targetport }}
  type: {{ .Values.rabbitmq.service.messaging.type }}
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Values.rabbitmq.ingressroute.name }}
  namespace: {{ .Values.rabbitmq.ingressroute.namespace }}
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`{{ .Values.rabbitmq.ingressroute.dns }}`)
      kind: Rule
      services:
        - name: rabbitmq-service
          port: {{ .Values.rabbitmq.service.management.port }}
  tls:
    secretName: tls-all