apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.sql.name }}
  namespace: {{ .Values.sql.namespace }}
spec:
  replicas: {{ .Values.sql.replicas }}
  selector:
    matchLabels:
      app: sql
  template:
    metadata:
      labels:
        app: sql
    spec:
      containers:
        - name: sql
          image: {{ .Values.sql.image.repository }}:{{ .Values.sql.image.tag }}
          ports:
            - containerPort: 1433
          env:
            - name: SA_PASSWORD
              value: {{ .Values.sql.db.password }}
---
apiVersion: v1
kind: Service
metadata:
  name: sql-service
  namespace: ynov
spec:
  selector:
    app: sql
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433