master:
  replicaCount: 1
  resources:
    limits:
      cpu: 500m      # Limite du CPU augmentée pour plus de puissance de traitement
      memory: 2Gi    # Mémoire augmentée pour une gestion améliorée du rôle master
    requests:
      cpu: 250m      # Demande du CPU ajustée pour le rôle master
      memory: 1Gi    # Demande de mémoire ajustée pour mieux supporter la charge

data:
  env:
    - name: ES_JAVA_OPTS
      value: "-Xms2g -Xmx2g"  # Alloue 2Go de mémoire pour le heap
  replicaCount: 1
  resources:
    limits:
      cpu: 1
      memory: 8Gi
    requests:
      cpu: 500m
      memory: 4Gi
   # Demande de mémoire adaptée aux tâches de stockage et traitement

ingest:
  replicaCount: 1
  resources:
    limits:
      cpu: 500m      # Limite CPU augmentée pour un meilleur traitement des flux d'ingestion
      memory: 2Gi    # Augmentation de la mémoire pour l'ingestion de données
    requests:
      cpu: 250m      # Demande CPU ajustée pour l'ingestion
      memory: 1Gi    # Demande mémoire augmentée pour éviter la surcharge
coordinating:
  replicaCount: 1
  resources:
    limits:
      cpu: 500m
      memory: 2Gi
    requests:
      cpu: 250m
      memory: 1Gi

copyTlsCerts:
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 50m
      memory: 64Mi

sysctlImage:
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 50m
      memory: 64Mi

readinessProbe:
  httpGet:
    path: /_cluster/health
    port: 9200
  initialDelaySeconds: 30
  periodSeconds: 10

livenessProbe:
  httpGet:
    path: /_cluster/health
    port: 9200
  initialDelaySeconds: 60
  periodSeconds: 20
elasticsearchUsername: "elastic"
elasticsearchPassword: "Btssio75000"