apiVersion: v1
kind: ConfigMap
metadata:
  name: elk-logstash
  namespace: monitoring
  labels:
    app.kubernetes.io/instance: elk-logstash
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: logstash
    app.kubernetes.io/version: "8.17.2"
    helm.sh/chart: logstash-6.4.4
data:
  logstash.conf: |
    input {
      http {
        port => 8080
      }
    }

    output {
      elasticsearch {
        hosts => ["${ELASTICSEARCH_HOST}:${ELASTICSEARCH_PORT}"]
        manage_template => false
        index => "%{[@metadata][beat]}-%{+YYYY.MM.dd}"
      }
      stdout {}
    }
